spring.application.name=deviceConfigapi
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/device_config
spring.datasource.username=root
spring.datasource.password=chaitanya@c
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
