spring.application.name=inventory-api
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/calsoft_inventory
spring.datasource.username=root
spring.datasource.password=chaitanya@c
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
